name: Linter
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: action/setup-node@v3
        with: 
          node-version: '20.x'
      - run: yarn
      - run: yarn lint
      - run: yarn ts-lint
      - run: yarn build
